{% set name = "streptofile" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/streptofile-{{ version }}.tar.gz
  sha256: fcfd30aa1a9615c0e1e6abffbb3792010e721ab14be312b852b6db4fd900c0b2

build:
  entry_points:
    - streptofile = streptofile.run_streptofile:main
    - emm_typer = streptofile.emm_typer:main
    - mlstyper = streptofile.mlstyper:main
    - virulence_profiler = streptofile.virulence_profiler:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.14
    - uv-build
    - pip
  run:
    - python >=3.14
    - polars
    - python-dotenv
    - blast

test:
  imports:
    - streptofile
  commands:
    - pip check
    - streptofile --help
    - emm_typer --help
    - mlstyper --help
    - virulence_profiler --help
  requires:
    - pip

about:
  summary: EMM typing, MLST and Virulence gene detection for S. pyogenes whole-genome sequencing data
  license: MIT

extra:
  recipe-maintainers:
    - thej-ssi
