{% set name = "streptofile" %}
{% set version = "0.4.6" %}
package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/streptofile-{{ version }}.tar.gz
  sha256: 226501e5181bb308caf305dd2e8236d71d7f0e07cfb019fac83bae21dd62f1ae
build:
  entry_points:
    - streptofile = streptofile.run_streptofile:main
    - emm_typer = streptofile.emm_typer:main
    - mlstyper = streptofile.mlstyper:main
    - virulence_profiler = streptofile.virulence_profiler:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0



requirements:
  host:
    - python >=3.14
    - uv-build
    - pip
  run:
    - python >=3.14
    - polars
    - python-dotenv
    - blast

test:
  imports:
    - streptofile
  commands:
    - pip check
    - streptofile --help
    - emm_typer --help
    - mlstyper --help
    - virulence_profiler --help
  requires:
    - pip

about:
  summary: EMM typing, MLST and Virulence gene detection for S. pyogenes whole-genome sequencing data
  license: MIT

extra:
  recipe-maintainers:
    - thej-ssi
